leftnav:
- identifier: 7ae075f3-7113-4cca-8784-05f7598ddaf6
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: d8e25c06-fb12-463b-a1e3-ae45fa0b4380
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 9f4cd9da-d27b-4eab-8328-ac98de355060
  name: Readings and Videos
  url: /pages/readings-and-videos
  weight: 30
